[package]
name = "mdo"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"

[dependencies]
base64 = "0.22"
comrak = { version = "0.54", default-features = false, features = [
    "shortcodes",
    "syntect-fancy",
] }
opener = "0.8"
sha2 = "0.10"

[profile.release]
lto = true
codegen-units = 1
strip = true
